### ISSUE TITLE
grunt build:js issue

### ISSUE THREAD

**Issue by scottschafer** [dpwolfe/otucha#13]
I'm on a Mac (OS 10.10) with all the tools installed (node 0.12.7, cmake 3.2.1, emscripten 1.34.4). I've put emscripten on my system path so I can emcc and emmake from anywhere and have successfully compiled with emscripten.

When I ran "grunt cmake:xcode" in the otucha directory, it worked great. The project was generated and built perfectly.

When I run "grunt build:js", I get the following:

Running "build:js" task
Running "shell:emscripten_cmake" (shell) task
Running "shell:emscripten_cmake" (shell) task
Running "shell:emscripten_make" (shell) task
Warning: Command failed: /bin/sh -c cd embuild&&make
make: \* No targets specified and no makefile found.  Stop.
 Use --force to continue.

**Comment by scottschafer** [comment]
Fixed!

I replaced "MinGW Makefiles" with "Unix Makefiles" in Gruntfile.js, and it built!

**Comment by scottschafer** [comment]
Unfortunately, that didn't solve the problem. I got it to build, but it would abort() early with errors indicating that objects were being cast into the wrong type. I don't think this is actually a problem in the code.

I next installed Ubuntu to a virtual machine, set it up per the instructions and hit the same wall.

Next up I will try Windows. I would _really_ like to get the emscripten compilation working on Mac or Linux though.

**Comment by dpwolfe** [comment]
Sorry for the delayed reply. I'd really like it to work as well. I am actually planning to return to continuing work in this project soon. I'm now on Windows 10 going through my own setup instructions, finding issues. I'll definitely ensure I'm working on Mac again as the whole point is to be cross-platform.  That "MinGW Makefiles" bit in the gruntfile is an ugly part that I did not expect to continue to work correctly in Linux, but it had been working in the past for me on Mac and in Linux via Travis-CI, which might provide some insight into why it works. I think Travis-CI may have Mac machines generally available, so I'll also work to enable that next as well.

**Comment by dpwolfe** [comment]
I flattened my MacBook Air with a new install of Yosemite and just got my dev environment set back up. Getting close to working on this.

**Comment by dpwolfe** [comment]
As I'm installing and waiting for clang to compile I realized that the version of Emscripten may have been critically important. I believe I was using 1.27 at the time, but I'm not going to bother installing that old version. I'll just use latest now and see what breaks.

**Comment by dpwolfe** [comment]
@scottschafer: I definitely needed your fix to use "Unix Makefiles" and will only use "MinGW Makefiles" on Windows now. I'm not sure why that ever worked on Mac, but maybe the generator used to come with the Mac CMake install anyway. It's working again, using all the latest versions of the dependencies. I made a lot of updates to the instructions as I stepped through them. It could be something that a later version of Emscripten fixed as I only grabbed latest, using 1.35.4, and it is working well. I've added version numbers to the README.

**Comment by dpwolfe** [comment]
@scottschafer: Also, based on errors I saw a long the way, I did see exactly the errors you were running into. Confused, I went back to the Emscripten instructions and found a missing step. I added a suggestion to create an `initem` alias, that will call the Emscripten emsdk_env.sh to setup the shell with paths that Emscripten requires. Run that before running `grunt build:js`. It changes what clang and node version you are pointing to, so I'd suggest only running it in a bash prompt used just for compiling Emscripten. If you setup paths a different way, you may be pointing to versions that are incompatible with Emscripten, getting various strange compiler and link errors. Thanks again and let me know if you run into any more issues.
