### ISSUE TITLE
Minor documentation issue

### ISSUE THREAD

**Issue by scottschafer** [dpwolfe/otucha#14]
On XCode, you won't see the copper cube as advertised unless you switch from the ALL_BUILD target to "otucha" and select Run. This may seem small, but it wasn't initially obvious to me.

**Comment by dpwolfe** [comment]
Thanks! Sorry that I just noticed this.

**Comment by dpwolfe** [comment]
@scottschafer: I updated the documentation. Thanks for letting me know. I tripped myself up on this as well today. :+1:
